### ISSUE TITLE
Add Shipping & Returns policy

### ISSUE THREAD

**Issue by huguestennier** [netlify/swag-site#23]
Currently it returns a 404: https://deploy-preview-15--swag.netlify.app/shipping-returns

**Comment by bigash42** [comment]
Copy for returns and exchanges policy: 

**Returns and Exchanges**
We want you to love your gear as much as we do. We will accept returns and exchanges of items in their original, unworn condition. Although we will not charge re-stocking fees, you will be responsible for shipping your item back to our facility.

**Return and Exchange Exceptions**
Worn, used, or altered merchandise will not be accepted for return or exchange.

**How To Return or Exchange An Item**
A return or exchange is as simple as sending an email to swagstore@netlify.com that includes the following information:

- Your full name
- Purchase date and/or order number
- Reason for the return/exchange
- Return product information (product, style, color and size)
- Exchange product information, when applicable (product, style, color and size)

We will respond with authorization and instructions that will help ensure your return/exchange is processed as quickly as possible. When shipping items back we recommend using a traceable carrier like USPS, UPS, or FedEx — we are not responsible for items not received.
