### ISSUE TITLE
Netlify swag logo looks pixelated on Desktop Safari

### ISSUE THREAD

**Issue by huguestennier** [netlify/swag-site#31]
Didn't investigate all other browser, but looks weird on desktop safari:

<img width="335" alt="Screen Shot 2020-07-16 at 9 27 32 PM" src="https://user-images.githubusercontent.com/6691035/87738384-3de56400-c7ab-11ea-95ee-b299eeca32cb.png">

Edit: Same thing on mobile Safari

Looks fine on Chrome.

**Comment by sdras** [comment]
Should be converted to an SVG
